# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QQ3hLblDY4wP6rZtuXqqdZQijcw7QFTJ
"""

import streamlit as st
import random
import math
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle, Polygon, Circle, Arc

# ============================================================
# CONFIGURAÇÃO DA PÁGINA
# ============================================================

st.set_page_config(
    page_title="Geometry Adventure - Mestre das Formas",
    page_icon="📐",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ============================================================
# ESTILO VISUAL
# ============================================================

st.markdown("""
<style>
    .main-title {
        font-size: 42px;
        font-weight: 800;
        text-align: center;
        margin-bottom: 5px;
    }

    .subtitle {
        text-align: center;
        font-size: 20px;
        margin-bottom: 25px;
    }

    .question-card {
        padding: 25px;
        border-radius: 20px;
        border: 2px solid #d9e6f2;
        background-color: #f8fbff;
        margin-top: 15px;
        margin-bottom: 20px;
    }

    .question-number {
        font-size: 18px;
        font-weight: bold;
    }

    .question-text {
        font-size: 25px;
        font-weight: 700;
        margin-top: 10px;
        margin-bottom: 15px;
    }

    .difficulty-easy {
        background-color: #dff6e4;
        padding: 5px 12px;
        border-radius: 20px;
        font-weight: bold;
    }

    .difficulty-medium {
        background-color: #fff1c7;
        padding: 5px 12px;
        border-radius: 20px;
        font-weight: bold;
    }

    .difficulty-hard {
        background-color: #ffdede;
        padding: 5px 12px;
        border-radius: 20px;
        font-weight: bold;
    }

    .score-box {
        padding: 15px;
        border-radius: 15px;
        text-align: center;
        background-color: #f0f7ff;
        border: 2px solid #c9e2ff;
    }

    .achievement {
        text-align: center;
        font-size: 28px;
        font-weight: 800;
        padding: 20px;
        border-radius: 20px;
        background-color: #fff9db;
        border: 3px solid #f2d16b;
    }

    .small-note {
        font-size: 15px;
        color: #666666;
    }

    div.stButton > button {
        width: 100%;
        border-radius: 12px;
        font-size: 18px;
        font-weight: 700;
        padding: 10px;
    }
</style>
""", unsafe_allow_html=True)


# ============================================================
# BANCO DE 20 PERGUNTAS
# ============================================================

QUESTIONS = [

    # --------------------------------------------------------
    # 1
    # --------------------------------------------------------
    {
        "question": "Observe a figura. Quantos lados tem um triângulo?",
        "options": ["2", "3", "4", "5"],
        "answer": "3",
        "difficulty": "Fácil",
        "explanation": "Um triângulo possui exatamente 3 lados e 3 vértices.",
        "diagram": "triangle"
    },

    # --------------------------------------------------------
    # 2
    # --------------------------------------------------------
    {
        "question": "Quantos vértices tem um quadrado?",
        "options": ["3", "4", "5", "6"],
        "answer": "4",
        "difficulty": "Fácil",
        "explanation": "Um quadrado possui 4 lados e, consequentemente, 4 vértices.",
        "diagram": "square"
    },

    # --------------------------------------------------------
    # 3
    # --------------------------------------------------------
    {
        "question": "Quantos lados tem um pentágono?",
        "options": ["4", "5", "6", "8"],
        "answer": "5",
        "difficulty": "Fácil",
        "explanation": "O prefixo 'penta' significa cinco. Portanto, um pentágono tem 5 lados.",
        "diagram": "pentagon"
    },

    # --------------------------------------------------------
    # 4
    # --------------------------------------------------------
    {
        "question": "Quantos lados possui um hexágono?",
        "options": ["5", "6", "7", "8"],
        "answer": "6",
        "difficulty": "Fácil",
        "explanation": "Um hexágono é um polígono com 6 lados e 6 vértices.",
        "diagram": "hexagon"
    },

    # --------------------------------------------------------
    # 5
    # --------------------------------------------------------
    {
        "question": "Quantos lados possui um octógono?",
        "options": ["6", "7", "8", "10"],
        "answer": "8",
        "difficulty": "Fácil",
        "explanation": "Um octógono possui 8 lados e 8 vértices.",
        "diagram": "octagon"
    },

    # --------------------------------------------------------
    # 6
    # --------------------------------------------------------
    {
        "question": "Um cubo tem quantas faces?",
        "options": ["4", "6", "8", "12"],
        "answer": "6",
        "difficulty": "Médio",
        "explanation": "Um cubo possui 6 faces quadradas, 12 arestas e 8 vértices.",
        "diagram": "cube"
    },

    # --------------------------------------------------------
    # 7
    # --------------------------------------------------------
    {
        "question": "Quantas arestas tem um paralelepípedo retângulo (caixa retangular)?",
        "options": ["6", "8", "10", "12"],
        "answer": "12",
        "difficulty": "Médio",
        "explanation": "Um paralelepípedo retângulo possui 12 arestas, 8 vértices e 6 faces.",
        "diagram": "cuboid"
    },

    # --------------------------------------------------------
    # 8
    # --------------------------------------------------------
    {
        "question": "Um depósito rural usa um tanque com forma de cilindro. Qual sólido geométrico representa o tanque?",
        "options": ["Cubo", "Cilindro", "Cone", "Esfera"],
        "answer": "Cilindro",
        "difficulty": "Médio",
        "explanation": "Um tanque cilíndrico possui duas bases circulares e uma superfície lateral curva.",
        "diagram": "cylinder"
    },

    # --------------------------------------------------------
    # 9
    # --------------------------------------------------------
    {
        "question": "Quantos vértices tem um cone?",
        "options": ["0", "1", "2", "3"],
        "answer": "1",
        "difficulty": "Médio",
        "explanation": "Um cone possui uma base circular e um vértice no ponto onde a superfície termina.",
        "diagram": "cone"
    },

    # --------------------------------------------------------
    # 10
    # --------------------------------------------------------
    {
        "question": "Um ângulo menor que 90° é chamado de:",
        "options": ["Ângulo reto", "Ângulo obtuso", "Ângulo agudo", "Ângulo raso"],
        "answer": "Ângulo agudo",
        "difficulty": "Fácil",
        "explanation": "Um ângulo agudo mede menos de 90°.",
        "diagram": "acute"
    },

    # --------------------------------------------------------
    # 11
    # --------------------------------------------------------
    {
        "question": "Um ângulo que mede exatamente 90° é chamado de:",
        "options": ["Agudo", "Reto", "Obtuso", "Raso"],
        "answer": "Reto",
        "difficulty": "Fácil",
        "explanation": "Um ângulo reto mede exatamente 90°.",
        "diagram": "right"
    },

    # --------------------------------------------------------
    # 12
    # --------------------------------------------------------
    {
        "question": "Um ângulo que mede mais de 90° e menos de 180° é:",
        "options": ["Agudo", "Reto", "Obtuso", "Completo"],
        "answer": "Obtuso",
        "difficulty": "Médio",
        "explanation": "Um ângulo obtuso é maior que 90° e menor que 180°.",
        "diagram": "obtuse"
    },

    # --------------------------------------------------------
    # 13
    # --------------------------------------------------------
    {
        "question": "Um retângulo tem 8 m de comprimento e 5 m de largura. Qual é o seu perímetro?",
        "options": ["13 m", "26 m", "40 m", "80 m"],
        "answer": "26 m",
        "difficulty": "Médio",
        "explanation": "Perímetro = 2 × (comprimento + largura) = 2 × (8 + 5) = 26 m.",
        "diagram": "rectangle_measure"
    },

    # --------------------------------------------------------
    # 14
    # --------------------------------------------------------
    {
        "question": "Um quadrado tem lado de 6 m. Qual é a sua área?",
        "options": ["12 m²", "24 m²", "36 m²", "42 m²"],
        "answer": "36 m²",
        "difficulty": "Médio",
        "explanation": "Área do quadrado = lado × lado = 6 × 6 = 36 m².",
        "diagram": "square_measure"
    },

    # --------------------------------------------------------
    # 15
    # --------------------------------------------------------
    {
        "question": "Uma horta retangular mede 10 m de comprimento e 4 m de largura. Qual é a área da horta?",
        "options": ["14 m²", "28 m²", "40 m²", "80 m²"],
        "answer": "40 m²",
        "difficulty": "Difícil",
        "explanation": "Área do retângulo = comprimento × largura = 10 × 4 = 40 m².",
        "diagram": "garden"
    },

    # --------------------------------------------------------
    # 16
    # --------------------------------------------------------
    {
        "question": "Qual destas figuras é um exemplo de polígono regular?",
        "options": [
            "Um quadrado com todos os lados iguais",
            "Um retângulo com lados de tamanhos diferentes",
            "Um triângulo com três lados diferentes",
            "Uma figura sem lados retos"
        ],
        "answer": "Um quadrado com todos os lados iguais",
        "difficulty": "Difícil",
        "explanation": "Um polígono regular possui lados e ângulos de mesma medida. O quadrado é um exemplo de polígono regular.",
        "diagram": "square"
    },

    # --------------------------------------------------------
    # 17
    # --------------------------------------------------------
    {
        "question": "Um polígono tem 7 lados. Como ele é chamado?",
        "options": ["Hexágono", "Heptágono", "Octógono", "Pentágono"],
        "answer": "Heptágono",
        "difficulty": "Difícil",
        "explanation": "Um polígono com 7 lados é chamado de heptágono.",
        "diagram": "heptagon"
    },

    # --------------------------------------------------------
    # 18
    # --------------------------------------------------------
    {
        "question": "Um campo de futebol retangular mede 30 m de comprimento e 20 m de largura. Qual é o perímetro do campo?",
        "options": ["50 m", "60 m", "100 m", "600 m"],
        "answer": "100 m",
        "difficulty": "Difícil",
        "explanation": "Perímetro = 2 × (30 + 20) = 2 × 50 = 100 m.",
        "diagram": "football"
    },

    # --------------------------------------------------------
    # 19
    # --------------------------------------------------------
    {
        "question": "Uma janela retangular de uma sala mede 3 m de comprimento e 2 m de largura. Qual é a área da janela?",
        "options": ["5 m²", "6 m²", "10 m²", "12 m²"],
        "answer": "6 m²",
        "difficulty": "Difícil",
        "explanation": "Área = comprimento × largura = 3 × 2 = 6 m².",
        "diagram": "window"
    },

    # --------------------------------------------------------
    # 20
    # --------------------------------------------------------
    {
        "question": "O telhado de uma casa apresenta um ângulo de 120° em uma das suas partes. Como classificamos esse ângulo?",
        "options": ["Agudo", "Reto", "Obtuso", "Completo"],
        "answer": "Obtuso",
        "difficulty": "Difícil",
        "explanation": "Como 120° é maior que 90° e menor que 180°, trata-se de um ângulo obtuso.",
        "diagram": "roof"
    }
]


# ============================================================
# FUNÇÕES PARA DESENHAR FIGURAS GEOMÉTRICAS
# ============================================================

def create_figure():
    """Cria uma figura matplotlib simples para uma pergunta."""
    fig, ax = plt.subplots(figsize=(5, 3.2))

    ax.set_xlim(0, 10)
    ax.set_ylim(0, 7)
    ax.axis("off")

    return fig, ax


def draw_diagram(diagram_type):
    """Desenha o diagrama correspondente à pergunta."""

    fig, ax = create_figure()

    # --------------------------------------------------------
    # TRIÂNGULO
    # --------------------------------------------------------
    if diagram_type == "triangle":
        points = [(2, 1), (5, 6), (8, 1)]
        polygon = Polygon(points, closed=True, fill=False, linewidth=3)
        ax.add_patch(polygon)
        ax.text(5, 0.3, "Triângulo", ha="center", fontsize=14)

    # --------------------------------------------------------
    # QUADRADO
    # --------------------------------------------------------
    elif diagram_type == "square":
        square = Rectangle((3, 1.5), 4, 4, fill=False, linewidth=3)
        ax.add_patch(square)
        ax.text(5, 0.5, "Quadrado", ha="center", fontsize=14)

    # --------------------------------------------------------
    # PENTÁGONO
    # --------------------------------------------------------
    elif diagram_type == "pentagon":
        angles = [90, 18, -54, -126, 162]
        points = []

        for angle in angles:
            rad = math.radians(angle)
            points.append(
                (5 + 2.5 * math.cos(rad),
                 3.5 + 2.5 * math.sin(rad))
            )

        polygon = Polygon(points, closed=True, fill=False, linewidth=3)
        ax.add_patch(polygon)
        ax.text(5, 0.4, "Pentágono", ha="center", fontsize=14)

    # --------------------------------------------------------
    # HEXÁGONO
    # --------------------------------------------------------
    elif diagram_type == "hexagon":
        points = []
        for i in range(6):
            angle = math.radians(60 * i)
            points.append(
                (5 + 2.5 * math.cos(angle),
                 3.5 + 2.5 * math.sin(angle))
            )

        polygon = Polygon(points, closed=True, fill=False, linewidth=3)
        ax.add_patch(polygon)
        ax.text(5, 0.3, "Hexágono", ha="center", fontsize=14)

    # --------------------------------------------------------
    # OCTÓGONO
    # --------------------------------------------------------
    elif diagram_type == "octagon":
        points = []
        for i in range(8):
            angle = math.radians(22.5 + i * 45)
            points.append(
                (5 + 2.4 * math.cos(angle),
                 3.5 + 2.4 * math.sin(angle))
            )

        polygon = Polygon(points, closed=True, fill=False, linewidth=3)
        ax.add_patch(polygon)
        ax.text(5, 0.3, "Octógono", ha="center", fontsize=14)

    # --------------------------------------------------------
    # HEPTÁGONO
    # --------------------------------------------------------
    elif diagram_type == "heptagon":
        points = []
        for i in range(7):
            angle = math.radians(90 + i * (360 / 7))
            points.append(
                (5 + 2.4 * math.cos(angle),
                 3.5 + 2.4 * math.sin(angle))
            )

        polygon = Polygon(points, closed=True, fill=False, linewidth=3)
        ax.add_patch(polygon)
        ax.text(5, 0.3, "Heptágono", ha="center", fontsize=14)

    # --------------------------------------------------------
    # CUBO
    # --------------------------------------------------------
    elif diagram_type == "cube":
        # Frente
        front = Polygon(
            [(2, 1.5), (5.5, 1.5), (5.5, 5), (2, 5)],
            closed=True,
            fill=False,
            linewidth=2.5
        )

        # Trás
        back = Polygon(
            [(4, 3), (7.5, 3), (7.5, 6.5), (4, 6.5)],
            closed=True,
            fill=False,
            linewidth=2.5
        )

        ax.add_patch(front)
        ax.add_patch(back)

        # Ligações
        connections = [
            ((2, 1.5), (4, 3)),
            ((5.5, 1.5), (7.5, 3)),
            ((5.5, 5), (7.5, 6.5)),
            ((2, 5), (4, 6.5))
        ]

        for start, end in connections:
            ax.plot(
                [start[0], end[0]],
                [start[1], end[1]],
                linewidth=2.5
            )

        ax.text(5, 0.4, "Cubo", ha="center", fontsize=14)

    # --------------------------------------------------------
    # PARALELEPÍPEDO
    # --------------------------------------------------------
    elif diagram_type == "cuboid":
        front = Polygon(
            [(1.5, 1.5), (6, 1.5), (6, 4.8), (1.5, 4.8)],
            closed=True,
            fill=False,
            linewidth=2.5
        )

        back = Polygon(
            [(3.5, 3), (8, 3), (8, 6.3), (3.5, 6.3)],
            closed=True,
            fill=False,
            linewidth=2.5
        )

        ax.add_patch(front)
        ax.add_patch(back)

        connections = [
            ((1.5, 1.5), (3.5, 3)),
            ((6, 1.5), (8, 3)),
            ((6, 4.8), (8, 6.3)),
            ((1.5, 4.8), (3.5, 6.3))
        ]

        for start, end in connections:
            ax.plot(
                [start[0], end[0]],
                [start[1], end[1]],
                linewidth=2.5
            )

        ax.text(5, 0.4, "Caixa retangular", ha="center", fontsize=14)

    # --------------------------------------------------------
    # CILINDRO
    # --------------------------------------------------------
    elif diagram_type == "cylinder":
        theta = [i * 2 * math.pi / 100 for i in range(101)]

        x = [5 + 2.2 * math.cos(t) for t in theta]
        y = [5.5 + 0.7 * math.sin(t) for t in theta]

        ax.plot(x, y, linewidth=2.5)

        x2 = [5 + 2.2 * math.cos(t) for t in theta]
        y2 = [2 + 0.7 * math.sin(t) for t in theta]

        ax.plot(x2, y2, linewidth=2.5)

        ax.plot([2.8, 2.8], [2, 5.5], linewidth=2.5)
        ax.plot([7.2, 7.2], [2, 5.5], linewidth=2.5)

        ax.text(5, 0.4, "Cilindro", ha="center", fontsize=14)

    # --------------------------------------------------------
    # CONE
    # --------------------------------------------------------
    elif diagram_type == "cone":
        theta = [i * 2 * math.pi / 100 for i in range(101)]

        x = [5 + 2.4 * math.cos(t) for t in theta]
        y = [1.5 + 0.7 * math.sin(t) for t in theta]

        ax.plot(x, y, linewidth=2.5)

        ax.plot([2.6, 5], [1.5, 6], linewidth=2.5)
        ax.plot([7.4, 5], [1.5, 6], linewidth=2.5)

        ax.scatter([5], [6], s=60)
        ax.text(5, 0.4, "Cone", ha="center", fontsize=14)

    # --------------------------------------------------------
    # ÂNGULO AGUDO
    # --------------------------------------------------------
    elif diagram_type == "acute":
        ax.plot([2, 2], [1.5, 5.5], linewidth=3)
        ax.plot([2, 1.5], [2, 4.5], linewidth=3)

        arc = Arc(
            (2, 2),
            2,
            2,
            angle=0,
            theta1=78,
            theta2=90,
            linewidth=3
        )
        ax.add_patch(arc)

        ax.text(5, 3.5, "< 90°", fontsize=22, fontweight="bold")
        ax.text(5, 0.4, "Ângulo agudo", ha="center", fontsize=14)

    # --------------------------------------------------------
    # ÂNGULO RETO
    # --------------------------------------------------------
    elif diagram_type == "right":
        ax.plot([2, 2], [1.5, 5.5], linewidth=3)
        ax.plot([2, 7], [2, 2], linewidth=3)

        square_mark = Polygon(
            [(2, 2), (2, 3), (3, 3), (3, 2)],
            closed=True,
            fill=False,
            linewidth=2
        )
        ax.add_patch(square_mark)

        ax.text(4.5, 4, "90°", fontsize=22, fontweight="bold")
        ax.text(5, 0.4, "Ângulo reto", ha="center", fontsize=14)

    # --------------------------------------------------------
    # ÂNGULO OBTUSO
    # --------------------------------------------------------
    elif diagram_type == "obtuse":
        ax.plot([2, 8], [2, 2], linewidth=3)
        ax.plot([2, 5], [2, 5.5], linewidth=3)

        arc = Arc(
            (2, 2),
            2.5,
            2.5,
            angle=0,
            theta1=0,
            theta2=55,
            linewidth=3
        )
        ax.add_patch(arc)

        ax.text(5, 4.3, "> 90°", fontsize=22, fontweight="bold")
        ax.text(5, 0.4, "Ângulo obtuso", ha="center", fontsize=14)

    # --------------------------------------------------------
    # RETÂNGULO COM MEDIDAS
    # --------------------------------------------------------
    elif diagram_type == "rectangle_measure":
        rect = Rectangle(
            (2, 2),
            6,
            2.5,
            fill=False,
            linewidth=3
        )
        ax.add_patch(rect)

        ax.text(5, 4.9, "8 m", ha="center", fontsize=16)
        ax.text(8.4, 3.2, "5 m", va="center", fontsize=16)
        ax.text(5, 0.4, "Retângulo", ha="center", fontsize=14)

    # --------------------------------------------------------
    # QUADRADO COM MEDIDA
    # --------------------------------------------------------
    elif diagram_type == "square_measure":
        square = Rectangle(
            (3, 1.5),
            4,
            4,
            fill=False,
            linewidth=3
        )
        ax.add_patch(square)

        ax.text(5, 5.8, "6 m", ha="center", fontsize=16)
        ax.text(7.5, 3.5, "6 m", va="center", fontsize=16)
        ax.text(5, 0.4, "Quadrado", ha="center", fontsize=14)

    # --------------------------------------------------------
    # HORTA
    # --------------------------------------------------------
    elif diagram_type == "garden":
        rect = Rectangle(
            (1.5, 1.5),
            7,
            3.5,
            fill=False,
            linewidth=3
        )
        ax.add_patch(rect)

        ax.text(5, 5.4, "10 m", ha="center", fontsize=16)
        ax.text(8.8, 3.2, "4 m", va="center", fontsize=16)
        ax.text(5, 0.4, "Horta retangular", ha="center", fontsize=14)

    # --------------------------------------------------------
    # CAMPO DE FUTEBOL
    # --------------------------------------------------------
    elif diagram_type == "football":
        field = Rectangle(
            (1.2, 1.3),
            7.6,
            4.2,
            fill=False,
            linewidth=3
        )
        ax.add_patch(field)

        # Linha central
        ax.plot([5, 5], [1.3, 5.5], linewidth=2)

        # Círculo central
        circle = Circle(
            (5, 3.4),
            0.9,
            fill=False,
            linewidth=2
        )
        ax.add_patch(circle)

        ax.text(5, 6, "30 m", ha="center", fontsize=16)
        ax.text(9.1, 3.4, "20 m", va="center", fontsize=16)
        ax.text(5, 0.4, "Campo de futebol", ha="center", fontsize=14)

    # --------------------------------------------------------
    # JANELA
    # --------------------------------------------------------
    elif diagram_type == "window":
        outer = Rectangle(
            (2, 1.3),
            6,
            4,
            fill=False,
            linewidth=3
        )
        ax.add_patch(outer)

        # Divisões da janela
        ax.plot([5, 5], [1.3, 5.3], linewidth=2)
        ax.plot([2, 8], [3.3, 3.3], linewidth=2)

        ax.text(5, 5.7, "3 m", ha="center", fontsize=16)
        ax.text(8.5, 3.3, "2 m", va="center", fontsize=16)
        ax.text(5, 0.4, "Janela retangular", ha="center", fontsize=14)

    # --------------------------------------------------------
    # TELHADO
    # --------------------------------------------------------
    elif diagram_type == "roof":
        ax.plot([1.5, 5, 8.5], [2, 6, 2], linewidth=3)
        ax.plot([1.5, 8.5], [2, 2], linewidth=3)

        ax.text(5, 2.8, "120°", fontsize=22, fontweight="bold")
        ax.text(5, 0.4, "Ângulo do telhado", ha="center", fontsize=14)

    return fig


# ============================================================
# FUNÇÕES DO JOGO
# ============================================================

def initialize_game(student_name):
    """Inicia uma nova partida."""

    questions = random.sample(QUESTIONS, len(QUESTIONS))

    # Criar uma cópia para não alterar o banco original
    prepared_questions = []

    for q in questions:
        new_question = q.copy()

        # Embaralhar as alternativas
        new_question["options"] = random.sample(
            q["options"],
            len(q["options"])
        )

        prepared_questions.append(new_question)

    st.session_state.game_started = True
    st.session_state.game_finished = False
    st.session_state.student_name = student_name
    st.session_state.questions = prepared_questions
    st.session_state.current_question = 0
    st.session_state.score = 0
    st.session_state.correct_answers = 0
    st.session_state.incorrect_answers = 0
    st.session_state.answered = False
    st.session_state.last_answer_correct = False
    st.session_state.last_selected_answer = None


def reset_game():
    """Volta para a tela inicial."""

    st.session_state.game_started = False
    st.session_state.game_finished = False
    st.session_state.questions = []
    st.session_state.current_question = 0
    st.session_state.score = 0
    st.session_state.correct_answers = 0
    st.session_state.incorrect_answers = 0
    st.session_state.answered = False
    st.session_state.last_answer_correct = False
    st.session_state.last_selected_answer = None


def get_achievement(score):
    """Determina a conquista com base na pontuação."""

    if score >= 36:
        return "🏆 Geometry Champion", (
            "Excelente! Você demonstrou um domínio muito forte "
            "dos conceitos de geometria."
        )

    elif score >= 30:
        return "⭐ Geometry Expert", (
            "Muito bom! Você conhece muito bem as formas, "
            "ângulos e medidas geométricas."
        )

    elif score >= 20:
        return "🎯 Geometry Explorer", (
            "Bom trabalho! Você está desenvolvendo suas "
            "habilidades de geometria."
        )

    else:
        return "💪 Keep Practicing", (
            "Continue praticando! Cada desafio é uma oportunidade "
            "para aprender mais geometria."
        )


def answer_question(selected_answer, question):
    """Verifica a resposta e atualiza a pontuação."""

    if st.session_state.answered:
        return

    st.session_state.answered = True
    st.session_state.last_selected_answer = selected_answer

    if selected_answer == question["answer"]:
        st.session_state.score += 2
        st.session_state.correct_answers += 1
        st.session_state.last_answer_correct = True
    else:
        st.session_state.incorrect_answers += 1
        st.session_state.last_answer_correct = False


# ============================================================
# INICIALIZAÇÃO DO SESSION STATE
# ============================================================

if "game_started" not in st.session_state:
    st.session_state.game_started = False

if "game_finished" not in st.session_state:
    st.session_state.game_finished = False

if "questions" not in st.session_state:
    st.session_state.questions = []

if "current_question" not in st.session_state:
    st.session_state.current_question = 0

if "score" not in st.session_state:
    st.session_state.score = 0

if "correct_answers" not in st.session_state:
    st.session_state.correct_answers = 0

if "incorrect_answers" not in st.session_state:
    st.session_state.incorrect_answers = 0

if "answered" not in st.session_state:
    st.session_state.answered = False

if "last_answer_correct" not in st.session_state:
    st.session_state.last_answer_correct = False

if "last_selected_answer" not in st.session_state:
    st.session_state.last_selected_answer = None

if "student_name" not in st.session_state:
    st.session_state.student_name = ""


# ============================================================
# CABEÇALHO
# ============================================================

st.markdown(
    '<div class="main-title">📐 Geometry Adventure</div>',
    unsafe_allow_html=True
)

st.markdown(
    '<div class="subtitle">🌟 Mestre das Formas — Desafio de Geometria do 5.º Ano 🌟</div>',
    unsafe_allow_html=True
)


# ============================================================
# SIDEBAR
# ============================================================

with st.sidebar:
    st.header("🎮 Sobre o Jogo")

    st.write(
        """
        Bem-vindo ao **Geometry Adventure!**

        Responda a 20 desafios de geometria,
        ganhe pontos e conquiste uma medalha.
        """
    )

    st.divider()

    st.subheader("📊 Pontuação")

    st.write("✅ Resposta correta = **2 pontos**")
    st.write("❌ Resposta incorreta = **0 pontos**")
    st.write("🏆 Pontuação máxima = **40 pontos**")

    st.divider()

    st.subheader("🏅 Conquistas")

    st.write("🏆 36–40: Geometry Champion")
    st.write("⭐ 30–35: Geometry Expert")
    st.write("🎯 20–29: Geometry Explorer")
    st.write("💪 0–19: Keep Practicing")


# ============================================================
# TELA INICIAL
# ============================================================

if not st.session_state.game_started:

    st.markdown(
        """
        <div class="question-card">
            <h2>🚀 Bem-vindo, jovem matemático!</h2>
            <p style="font-size:20px;">
            Prepare-se para uma aventura pelas formas geométricas,
            ângulos, perímetros, áreas e sólidos geométricos!
            </p>
        </div>
        """,
        unsafe_allow_html=True
    )

    st.subheader("👤 Primeiro, escreva o seu nome")

    name = st.text_input(
        "Nome do aluno:",
        placeholder="Digite o seu nome aqui...",
        max_chars=50
    )

    st.write("")

    col1, col2, col3 = st.columns([1, 2, 1])

    with col2:
        start = st.button(
            "🚀 COMEÇAR O JOGO",
            use_container_width=True
        )

    if start:
        if not name.strip():
            st.warning("⚠️ Por favor, escreva o seu nome antes de começar.")
        else:
            initialize_game(name.strip())
            st.rerun()

    st.divider()

    st.info(
        """
        💡 **Dica:** Leia cada pergunta com atenção.
        Pense como um verdadeiro investigador de formas!
        """
    )

# ============================================================
# JOGO
# ============================================================

elif st.session_state.game_started and not st.session_state.game_finished:

    total_questions = len(st.session_state.questions)
    current = st.session_state.current_question
    question = st.session_state.questions[current]

    # --------------------------------------------------------
    # PAINEL SUPERIOR
    # --------------------------------------------------------

    col1, col2, col3 = st.columns(3)

    with col1:
        st.metric(
            "👤 Aluno",
            st.session_state.student_name
        )

    with col2:
        st.metric(
            "⭐ Pontos",
            st.session_state.score
        )

    with col3:
        st.metric(
            "✅ Corretas",
            st.session_state.correct_answers
        )

    progress = current / total_questions

    st.progress(
        progress,
        text=f"Progresso: {current} de {total_questions} perguntas"
    )

    st.markdown(
        f"""
        <div class="question-card">

            <div class="question-number">
                📘 Pergunta {current + 1} de {total_questions}
            </div>

            <div style="margin-top:10px;">
                <span class="difficulty-{question['difficulty'].lower().replace('í','i')}">
                    Nível: {question['difficulty']}
                </span>
            </div>

            <div class="question-text">
                {question['question']}
            </div>

        </div>
        """,
        unsafe_allow_html=True
    )

    # --------------------------------------------------------
    # DIAGRAMA
    # --------------------------------------------------------

    if question.get("diagram"):
        fig = draw_diagram(question["diagram"])
        st.pyplot(fig, use_container_width=True)
        plt.close(fig)

    # --------------------------------------------------------
    # RESPOSTAS
    # --------------------------------------------------------

    if not st.session_state.answered:

        selected = st.radio(
            "🧠 Escolha uma resposta:",
            question["options"],
            index=None,
            key=f"answer_{current}"
        )

        st.write("")

        submit = st.button(
            "✅ CONFIRMAR RESPOSTA",
            use_container_width=True
        )

        if submit:

            if selected is None:
                st.warning(
                    "⚠️ Escolha uma alternativa antes de confirmar."
                )
            else:
                answer_question(selected, question)
                st.rerun()

    # --------------------------------------------------------
    # FEEDBACK
    # --------------------------------------------------------

    else:

        if st.session_state.last_answer_correct:

            st.success(
                "🎉 Excelente! Você é uma Geometry Star!"
            )

            st.balloons()

            st.markdown(
                f"""
                **Sua resposta:** {st.session_state.last_selected_answer}

                🏆 Você ganhou **2 pontos**!
                """
            )

        else:

            st.error(
                "💡 Não foi desta vez. Vamos aprender com o erro!"
            )

            st.markdown(
                f"""
                **Sua resposta:** {st.session_state.last_selected_answer}

                **Resposta correta:** {question['answer']}
                """
            )

        st.info(
            f"📚 **Explicação:** {question['explanation']}"
        )

        st.write("")

        # ----------------------------------------------------
        # BOTÃO PRÓXIMA PERGUNTA
        # ----------------------------------------------------

        if current < total_questions - 1:

            if st.button(
                "➡️ PRÓXIMA PERGUNTA",
                use_container_width=True
            ):

                st.session_state.current_question += 1
                st.session_state.answered = False
                st.session_state.last_answer_correct = False
                st.session_state.last_selected_answer = None

                st.rerun()

        else:

            if st.button(
                "🏁 VER RESULTADO FINAL",
                use_container_width=True
            ):

                st.session_state.game_finished = True
                st.rerun()


# ============================================================
# RESULTADO FINAL
# ============================================================

elif st.session_state.game_finished:

    score = st.session_state.score
    correct = st.session_state.correct_answers
    incorrect = st.session_state.incorrect_answers

    percentage = (score / 40) * 100

    achievement, message = get_achievement(score)

    st.markdown(
        """
        <div class="question-card">
            <h1 style="text-align:center;">
                🎉 PARABÉNS! 🎉
            </h1>
            <h2 style="text-align:center;">
                Você terminou a aventura de geometria!
            </h2>
        </div>
        """,
        unsafe_allow_html=True
    )

    st.balloons()

    st.markdown(
        f"""
        <div class="achievement">
            {achievement}
        </div>
        """,
        unsafe_allow_html=True
    )

    st.write("")

    # --------------------------------------------------------
    # RESULTADOS
    # --------------------------------------------------------

    col1, col2, col3, col4 = st.columns(4)

    with col1:
        st.metric(
            "👤 Aluno",
            st.session_state.student_name
        )

    with col2:
        st.metric(
            "🏆 Pontos",
            f"{score}/40"
        )

    with col3:
        st.metric(
            "📈 Percentagem",
            f"{percentage:.0f}%"
        )

    with col4:
        st.metric(
            "✅ Corretas",
            correct
        )

    st.write("")

    col1, col2 = st.columns(2)

    with col1:
        st.metric(
            "❌ Incorretas",
            incorrect
        )

    with col2:
        st.metric(
            "📚 Perguntas",
            "20/20"
        )

    st.divider()

    st.subheader("🌟 Feedback")

    st.info(message)

    if score >= 36:
        st.success(
            "🏆 Excelente desempenho! "
            "Você está pronto para enfrentar novos desafios de geometria!"
        )

    elif score >= 30:
        st.success(
            "⭐ Muito bom! Continue praticando para chegar ao nível Champion!"
        )

    elif score >= 20:
        st.warning(
            "🎯 Bom trabalho! Revise algumas propriedades das figuras "
            "e tente novamente."
        )

    else:
        st.warning(
            "💪 Não desista! Reveja os conceitos de lados, vértices, "
            "ângulos, perímetro e área e jogue novamente."
        )

    st.write("")

    # --------------------------------------------------------
    # PLAY AGAIN
    # --------------------------------------------------------

    if st.button(
        "🔄 JOGAR NOVAMENTE",
        use_container_width=True
    ):
        reset_game()
        st.rerun()

    st.write("")

    st.caption(
        "📐 Geometry Adventure — Aprender geometria pode ser uma aventura!"
    )