# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mq3wYstIGg49UXE5D3_SnK5f4MWjhYxx
"""

```python
import streamlit as st
import random

# =========================================================
# PAGE CONFIGURATION
# =========================================================
st.set_page_config(
    page_title="Geometry Adventure - Grade 5",
    page_icon="📐",
    layout="centered"
)

# =========================================================
# CUSTOM CSS
# =========================================================
st.markdown("""
<style>
    .main-title {
        text-align: center;
        font-size: 42px;
        font-weight: bold;
        margin-bottom: 5px;
    }

    .subtitle {
        text-align: center;
        font-size: 20px;
        margin-bottom: 20px;
    }

    .question-box {
        padding: 20px;
        border-radius: 15px;
        border: 2px solid #4CAF50;
        margin: 10px 0;
    }

    .score-box {
        padding: 15px;
        border-radius: 15px;
        text-align: center;
        font-size: 24px;
        font-weight: bold;
    }
</style>
""", unsafe_allow_html=True)

# =========================================================
# TITLE
# =========================================================
st.markdown(
    '<div class="main-title">📐 Geometry Adventure</div>',
    unsafe_allow_html=True
)

st.markdown(
    '<div class="subtitle">🎮 Jogu Matemátika – Klase 5</div>',
    unsafe_allow_html=True
)

# =========================================================
# SESSION STATE
# =========================================================
if "started" not in st.session_state:
    st.session_state.started = False

if "question" not in st.session_state:
    st.session_state.question = 0

if "score" not in st.session_state:
    st.session_state.score = 0

if "answered" not in st.session_state:
    st.session_state.answered = False

if "finished" not in st.session_state:
    st.session_state.finished = False

if "feedback" not in st.session_state:
    st.session_state.feedback = ""

if "badge" not in st.session_state:
    st.session_state.badge = ""

# =========================================================
# MULTIPLE CHOICE QUESTIONS - 20
# =========================================================

mc_questions = [
    {
        "q": "1. Forma ne'ebé iha 3 lados mak saida?",
        "options": ["A. Quadrado", "B. Triângulo", "C. Pentágono", "D. Hexágono"],
        "answer": "B. Triângulo"
    },
    {
        "q": "2. Quadrado iha lados hira?",
        "options": ["A. 3", "B. 4", "C. 5", "D. 6"],
        "answer": "B. 4"
    },
    {
        "q": "3. Triângulo iha ângulu hira?",
        "options": ["A. 2", "B. 3", "C. 4", "D. 5"],
        "answer": "B. 3"
    },
    {
        "q": "4. Forma ne'ebé iha 5 lados mak?",
        "options": ["A. Pentágono", "B. Hexágono", "C. Triângulo", "D. Octógono"],
        "answer": "A. Pentágono"
    },
    {
        "q": "5. Forma ne'ebé iha 6 lados mak?",
        "options": ["A. Pentágono", "B. Hexágono", "C. Heptágono", "D. Quadrado"],
        "answer": "B. Hexágono"
    },
    {
        "q": "6. Perímetru quadrado ho lado 5 cm mak hira?",
        "options": ["A. 10 cm", "B. 15 cm", "C. 20 cm", "D. 25 cm"],
        "answer": "C. 20 cm"
    },
    {
        "q": "7. Área quadrado ho lado 4 cm mak?",
        "options": ["A. 8 cm²", "B. 12 cm²", "C. 16 cm²", "D. 20 cm²"],
        "answer": "C. 16 cm²"
    },
    {
        "q": "8. Retângulo ho comprimento 8 cm no largura 3 cm. Área mak?",
        "options": ["A. 11 cm²", "B. 18 cm²", "C. 24 cm²", "D. 30 cm²"],
        "answer": "C. 24 cm²"
    },
    {
        "q": "9. Perímetru retângulu ho comprimento 6 cm no largura 4 cm mak?",
        "options": ["A. 10 cm", "B. 20 cm", "C. 24 cm", "D. 28 cm"],
        "answer": "B. 20 cm"
    },
    {
        "q": "10. Ângulu 90° bolu sai ângulu saida?",
        "options": ["A. Ângulu agudu", "B. Ângulu reto", "C. Ângulu obtusu", "D. Ângulu rasu"],
        "answer": "B. Ângulu reto"
    },
    {
        "q": "11. Ângulu ki'ik liu husi 90° mak?",
        "options": ["A. Agudu", "B. Reto", "C. Obtusu", "D. Rasú"],
        "answer": "A. Agudu"
    },
    {
        "q": "12. Ângulu boot liu 90° maibé ki'ik liu 180° mak?",
        "options": ["A. Agudu", "B. Reto", "C. Obtusu", "D. Rasú"],
        "answer": "C. Obtusu"
    },
    {
        "q": "13. Forma ne'ebé iha 4 lados no lados hotu-hotu hanesan mak?",
        "options": ["A. Triângulo", "B. Quadrado", "C. Pentágono", "D. Círculo"],
        "answer": "B. Quadrado"
    },
    {
        "q": "14. Círculo iha lados retu hira?",
        "options": ["A. 0", "B. 1", "C. 2", "D. 4"],
        "answer": "A. 0"
    },
    {
        "q": "15. Triângulo ho lados hotu hanesan naran saida?",
        "options": [
            "A. Triângulo escaleno",
            "B. Triângulo isósceles",
            "C. Triângulo equilátero",
            "D. Triângulo reto"
        ],
        "answer": "C. Triângulo equilátero"
    },
    {
        "q": "16. Hexágono iha lados hira?",
        "options": ["A. 4", "B. 5", "C. 6", "D. 7"],
        "answer": "C. 6"
    },
    {
        "q": "17. Perímetru pentágono regular ho lado 4 cm mak?",
        "options": ["A. 9 cm", "B. 16 cm", "C. 20 cm", "D. 25 cm"],
        "answer": "C. 20 cm"
    },
    {
        "q": "18. Retângulo ho área 30 cm² no comprimento 6 cm. Largura mak?",
        "options": ["A. 4 cm", "B. 5 cm", "C. 6 cm", "D. 8 cm"],
        "answer": "B. 5 cm"
    },
    {
        "q": "19. Linha ne'ebé fahe forma
```