# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pKTKkOhCTrKk1tHqR8b77VGlbrRG3Es9
"""

```python
import streamlit as st
import random

# ==============================
# CONFIGURASAUN PÁJINA
# ==============================
st.set_page_config(
    page_title="Geometry Challenge - Grade 5",
    page_icon="📐",
    layout="centered"
)

# ==============================
# CSS - DESAIN ATRATIVU
# ==============================
st.markdown("""
<style>
.main-title {
    text-align: center;
    font-size: 42px;
    font-weight: bold;
}

.subtitle {
    text-align: center;
    font-size: 20px;
}

.question-box {
    padding: 20px;
    border-radius: 15px;
    border: 2px solid #4CAF50;
    background-color: #f7fff7;
    margin: 15px 0;
}

.score-box {
    padding: 15px;
    border-radius: 15px;
    text-align: center;
    font-size: 25px;
    font-weight: bold;
}
</style>
""", unsafe_allow_html=True)

# ==============================
# TÍTULU
# ==============================
st.markdown(
    '<div class="main-title">📐 GEOMETRY CHALLENGE</div>',
    unsafe_allow_html=True
)

st.markdown(
    '<div class="subtitle">🎮 Jogu Matemátika - Klase 5</div>',
    unsafe_allow_html=True
)

st.write("")

# ==============================
# PERGUNTAS
# ==============================
questions = [
    {
        "question": "Forma ida ne'ebé iha 3 lados mak saida?",
        "options": ["A. Quadrado", "B. Triângulo", "C. Pentágono", "D. Hexágono"],
        "answer": "B. Triângulo"
    },
    {
        "question": "Quadrado ida iha lados hira?",
        "options": ["A. 3", "B. 4", "C. 5", "D. 6"],
        "answer": "B. 4"
    },
    {
        "question": "Pentágono iha lados hira?",
        "options": ["A. 4", "B. 5", "C. 6", "D. 7"],
        "answer": "B. 5"
    },
    {
        "question": "Hexágono iha lados hira?",
        "options": ["A. 5", "B. 6", "C. 7", "D. 8"],
        "answer": "B. 6"
    },
    {
        "question": "Octógono iha lados hira?",
        "options": ["A. 6", "B. 7", "C. 8", "D. 9"],
        "answer": "C. 8"
    },
    {
        "question": "Quadrado ho lado 5 cm nia perímetru hira?",
        "options": ["A. 10 cm", "B. 15 cm", "C. 20 cm", "D. 25 cm"],
        "answer": "C. 20 cm"
    },
    {
        "question": "Quadrado ho lado 4 cm nia área hira?",
        "options": ["A. 8 cm²", "B. 12 cm²", "C. 16 cm²", "D. 20 cm²"],
        "answer": "C. 16 cm²"
    },
    {
        "question": "Retângulu ho comprimento 8 cm no largura 3 cm nia área hira?",
        "options": ["A. 11 cm²", "B. 18 cm²", "C. 24 cm²", "D. 30 cm²"],
        "answer": "C. 24 cm²"
    },
    {
        "question": "Retângulu ho comprimento 6 cm no largura 4 cm nia perímetru hira?",
        "options": ["A. 10 cm", "B. 20 cm", "C. 24 cm", "D. 28 cm"],
        "answer": "B. 20 cm"
    },
    {
        "question": "Ângulu 90° bolu saida?",
        "options": [
            "A. Ângulu agudu",
            "B. Ângulu reto",
            "C. Ângulu obtusu",
            "D. Ângulu rasu"
        ],
        "answer": "B. Ângulu reto"
    },
    {
        "question": "Ângulu menus husi 90° mak ângulu saida?",
        "options": [
            "A. Agudu",
            "B. Reto",
            "C. Obtusu",
            "D. Rasu"
        ],
        "answer": "A. Agudu"
    },
    {
        "question": "Ângulu entre 90° no 180° mak?",
        "options": [
            "A. Agudu",
            "B. Reto",
            "C. Obtusu",
            "D. Rasu"
        ],
        "answer": "C. Obtusu"
    },
    {
        "question": "Forma ida ne'ebé iha 4 lados hanesan no 4 ângulu reto mak?",
        "options": [
            "A. Triângulo",
            "B. Quadrado",
            "C. Pentágono",
            "D. Círculo"
        ],
        "answer": "B. Quadrado"
    },
    {
        "question": "Círculo iha lados retu hira?",
        "options": ["A. 0", "B. 1", "C. 2", "D. 4"],
        "answer": "A. 0"
    },
    {
        "question": "Triângulu ho lados hotu hanesan mak naran?",
        "options": [
            "A. Escaleno",
            "B. Isósceles",
            "C. Equilátero",
            "D. Obtusu"
        ],
        "answer": "C. Equilátero"
    },
    {
        "question": "Perímetru pentágono regular ho lado 4 cm mak?",
        "options": ["A. 12 cm", "B. 16 cm", "C. 20 cm", "D. 24 cm"],
        "answer": "C. 20 cm"
    },
    {
        "question": "Retângulu ho área 30 cm² no comprimento 6 cm. Largura hira?",
        "options": ["A. 3 cm", "B. 4 cm", "C. 5 cm", "D. 6 cm"],
        "answer": "C. 5 cm"
    },
    {
        "question": "Forma ida ho 7 lados bolu saida?",
        "options": [
            "A. Hexágono",
            "B. Heptágono",
            "C. Octógono",
            "D. Nonágono"
        ],
        "answer": "B. Heptágono"
    },
    {
        "question": "Forma ida ho 8 lados bolu saida?",
        "options": [
            "A. Hexágono",
            "B. Heptágono",
            "C. Octógono",
            "D. Nonágono"
        ],
        "answer": "C. Octógono"
    },
    {
        "question": "Triângulu ho lados 5 cm, 6 cm no 7 cm. Perímetru hira?",
        "options": ["A. 16 cm", "B. 18 cm", "C. 20 cm", "D. 21 cm"],
        "answer": "B. 18 cm"
    }
]

# ==============================
# SESSION STATE
# ==============================
if "started" not in st.session_state:
    st.session_state.started = False

if "q_index" not in st.session_state:
    st.session_state.q_index = 0

if "score" not in st.session_state:
    st.session_state.score = 0

if "answered" not in st.session_state:
    st.session_state.answered = False

if "feedback" not in st.session_state:
    st.session_state.feedback = ""

# ==============================
# INÍCIO JOGU
# ==============================
if not st.session_state.started:

    st.info("""
    🎯 **Objetivu Jogu**

    Responde pergunta 20 kona-ba geometria.

    ⭐ Resposta loos = **+2 pontu**

    🏆 Pontu máximu = **40 pontu**

    🎉 Tenta hetan pontu aas liu!
    """)

    if st.button("🚀 HAHÚ JOGU", use_container_width=True):

        st.session_state.started = True
        st.session_state.q_index = 0
        st.session_state.score = 0
        st.session_state.answered = False
        st.session_state.feedback = ""

        st.rerun()

# ==============================
# JOGU
# ==============================
else:

    index = st.session_state.q_index

    # ==========================
    # JOGU REMATA
    # ==========================
    if index >= len(questions):

        st.balloons()

        st.markdown("## 🎉 PARABÉNS! JOGU REMATA!")

        st.markdown(
            f"""
            <div class="score-box">
                🏆 SCORE: {st.session_state.score} / 40
            </div>
            """,
            unsafe_allow_html=True
        )

        score = st.session_state.score

        if score >= 36:
            st.success("🥇 GEOMETRY MASTER! Excelente tebes!")
        elif score >= 28:
            st.success("🥈 GEOMETRY EXPERT! Diak tebes!")
        elif score >= 20:
            st.info("🥉 GEOMETRY EXPLORER! Kontinua aprende!")
        else:
            st.warning("🌟 GEOMETRY BEGINNER! Pratika tan, ita bele!")

        st.write("")

        if st.button("🔄 JOGA TAN", use_container_width=True):

            st.session_state.started = False
            st.session_state.q_index = 0
            st.session_state.score = 0
            st.session_state.answered = False
            st.session_state.feedback = ""

            st.rerun()

    # ==========================
    # PERGUNTA
    # ==========================
    else:

        q = questions[index]

        # Progress
        st.progress(
            (index + 1) / len(questions)
        )

        st.write(
            f"### 📘 Pergunta {index + 1} / {len(questions)}"
        )

        st.markdown(
            f"""
            <div class="question-box">
                <h3>📐 {q["question"]}</h3>
            </div>
            """,
            unsafe_allow_html=True
        )

        answer = st.radio(
            "👇 Hili resposta loos:",
            q["options"],
            key=f"answer_{index}"
        )

        # ======================
        # KONFIRMA RESPOSTA
        # ======================
        if not st.session_state.answered:

            if st.button(
                "✅ KONFIRMA RESPOSTA",
                use_container_width=True
            ):

                if answer == q["answer"]:

                    st.session_state.score += 2

                    st.session_state.feedback = (
                        "🎉 **LOS!** Ita hetan +2 pontu! ⭐"
                    )

                    st.balloons()

                else:

                    st.session_state.feedback = (
                        f"❌ **SALA!** Resposta loos mak "
                        f"**{q['answer']}**."
                    )

                st.session_state.answered = True

                st.rerun()

        # ======================
        # FEEDBACK
        # ======================
        else:

            if "LOS" in st.session_state.feedback:
                st.success(st.session_state.feedback)
            else:
                st.error(st.session_state.feedback)

            st.write(
                f"🏆 **Pontu agora:** {st.session_state.score}"
            )

            if st.button(
                "➡️ PERGUNTA TUIR",
                use_container_width=True
            ):

                st.session_state.q_index += 1
                st.session_state.answered = False
                st.session_state.feedback = ""

                st.rerun()
```

### `requirements.txt`

Kriau file ida ho naran **`requirements.txt`**:

```text
streamlit
```

### Estrutura iha GitHub

```text
geometry-game/
│
├── app.py
└── requirements.txt
```

### Deploy ba Streamlit

1. Kria repository foun iha GitHub, hanesan **`geometry-game`**.
2. Upload `app.py`.
3. Upload `requirements.txt`.
4. Akses [Streamlit Community Cloud](https://share.streamlit.io/?utm_source=chatgpt.com).
5. Login ho GitHub.
6. Hili **New app**.
7. Hili repository `geometry-game`.
8. Iha **Main file path**, hili `app.py`.
9. Klik **Deploy**.

Depois ne'e, jogu bele uza iha browser liu husi link Streamlit.

**Estrutura pedagójika:** 20 perguntas × 2 pontu = **40 pontu**, no konténudu kobre forma geométrika, númeru lados, perímetru, área no klasifikasaun ângulu.