# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u-0zvdkLyzi13ZlSvSg0o2bh-C5ohYbu
"""

import streamlit as st
import random

# ============================================================
# KONFIGURASAUN PÁJINA
# ============================================================
st.set_page_config(
    page_title="Aventura Aritmétika - Klase 6",
    page_icon="🧮",
    layout="centered"
)

# ============================================================
# ESTILU
# ============================================================
st.markdown("""
<style>
.main {
    background-color: #f7f9fc;
}

.title {
    text-align: center;
    font-size: 42px;
    font-weight: bold;
    margin-bottom: 5px;
}

.subtitle {
    text-align: center;
    font-size: 20px;
    margin-bottom: 20px;
}

.level-box {
    padding: 15px;
    border-radius: 15px;
    text-align: center;
    margin-bottom: 15px;
}

.question-box {
    padding: 20px;
    border-radius: 18px;
    background-color: #ffffff;
    border: 2px solid #e5e7eb;
    margin-bottom: 20px;
}

.result-box {
    padding: 25px;
    border-radius: 20px;
    text-align: center;
    background-color: #ffffff;
    border: 2px solid #dbeafe;
}

.stButton > button {
    width: 100%;
    border-radius: 12px;
    font-size: 18px;
    padding: 10px;
}
</style>
""", unsafe_allow_html=True)

# ============================================================
# DADUS PERGUNTA
# ============================================================

perguntas = {

    "Fasil": [
        {
            "pergunta": "27 + 35 = ?",
            "opsaun": ["52", "62", "72", "60"],
            "los": "62",
            "explicasaun": "27 + 35 = 62."
        },
        {
            "pergunta": "84 - 29 = ?",
            "opsaun": ["55", "65", "45", "53"],
            "los": "55",
            "explicasaun": "84 - 29 = 55."
        },
        {
            "pergunta": "7 × 8 = ?",
            "opsaun": ["54", "56", "64", "48"],
            "los": "56",
            "explicasaun": "7 × 8 = 56."
        },
        {
            "pergunta": "72 ÷ 8 = ?",
            "opsaun": ["8", "9", "10", "12"],
            "los": "9",
            "explicasaun": "72 ÷ 8 = 9."
        },
        {
            "pergunta": "45 + 18 = ?",
            "opsaun": ["53", "63", "73", "61"],
            "los": "63",
            "explicasaun": "45 + 18 = 63."
        },
        {
            "pergunta": "100 - 46 = ?",
            "opsaun": ["54", "56", "64", "44"],
            "los": "54",
            "explicasaun": "100 - 46 = 54."
        }
    ],

    "Moderadu": [
        {
            "pergunta": "125 + 248 = ?",
            "opsaun": ["363", "373", "383", "393"],
            "los": "373",
            "explicasaun": "125 + 248 = 373."
        },
        {
            "pergunta": "500 - 275 = ?",
            "opsaun": ["215", "225", "235", "245"],
            "los": "225",
            "explicasaun": "500 - 275 = 225."
        },
        {
            "pergunta": "24 × 15 = ?",
            "opsaun": ["350", "360", "370", "340"],
            "los": "360",
            "explicasaun": "24 × 15 = 360."
        },
        {
            "pergunta": "360 ÷ 12 = ?",
            "opsaun": ["20", "25", "30", "35"],
            "los": "30",
            "explicasaun": "360 ÷ 12 = 30."
        },
        {
            "pergunta": "3/4 + 1/4 = ?",
            "opsaun": ["1/2", "3/4", "1", "2"],
            "los": "1",
            "explicasaun": "3/4 + 1/4 = 4/4 = 1."
        },
        {
            "pergunta": "2,5 + 1,75 = ?",
            "opsaun": ["4,15", "4,25", "4,35", "3,25"],
            "los": "4,25",
            "explicasaun": "2,50 + 1,75 = 4,25."
        }
    ],

    "Difisil": [
        {
            "pergunta": "48 + 36 ÷ 6 = ?",
            "opsaun": ["14", "54", "84", "90"],
            "los": "54",
            "explicasaun": "Primeiru halo divizaun: 36 ÷ 6 = 6. Depois 48 + 6 = 54."
        },
        {
            "pergunta": "(25 + 15) × 3 = ?",
            "opsaun": ["100", "110", "120", "130"],
            "los": "120",
            "explicasaun": "25 + 15 = 40; depois 40 × 3 = 120."
        },
        {
            "pergunta": "3 × (18 - 7) + 5 = ?",
            "opsaun": ["28", "32", "38", "40"],
            "los": "38",
            "explicasaun": "18 - 7 = 11; 3 × 11 = 33; 33 + 5 = 38."
        },
        {
            "pergunta": "¾ hosi 40 = ?",
            "opsaun": ["20", "25", "30", "35"],
            "los": "30",
            "explicasaun": "3/4 × 40 = 30."
        },
        {
            "pergunta": "Se 5 cadernu ida-idak custa $2,50, total hira?",
            "opsaun": ["$10,00", "$12,50", "$15,00", "$7,50"],
            "los": "$12,50",
            "explicasaun": "5 × $2,50 = $12,50."
        },
        {
            "pergunta": "600 ÷ (5 × 2) = ?",
            "opsaun": ["50", "60", "100", "120"],
            "los": "60",
            "explicasaun": "5 × 2 = 10; depois 600 ÷ 10 = 60."
        }
    ]
}

# ============================================================
# INICIALIZA SESSION STATE
# ============================================================

if "iniciado" not in st.session_state:
    st.session_state.iniciado = False

if "nome" not in st.session_state:
    st.session_state.nome = ""

if "nivel" not in st.session_state:
    st.session_state.nivel = "Fasil"

if "quiz" not in st.session_state:
    st.session_state.quiz = []

if "indice" not in st.session_state:
    st.session_state.indice = 0

if "pontuasaun" not in st.session_state:
    st.session_state.pontuasaun = 0

if "respondidu" not in st.session_state:
    st.session_state.respondidu = False

if "resposta_utilizador" not in st.session_state:
    st.session_state.resposta_utilizador = ""

if "terminado" not in st.session_state:
    st.session_state.terminado = False

# ============================================================
# TÍTULU
# ============================================================

st.markdown(
    "<div class='title'>🧮 AVENTURA ARITMÉTIKA</div>",
    unsafe_allow_html=True
)

st.markdown(
    "<div class='subtitle'>Jogu Matemátika ba Estudante Klase 6</div>",
    unsafe_allow_html=True
)

# ============================================================
# PÁJINA INISIU
# ============================================================

if not st.session_state.iniciado:

    st.info(
        "🎯 Objetivu: rezolve problema aritmétika no conquista pontu!"
    )

    nome = st.text_input(
        "👤 Hakerek naran:",
        placeholder="Ezemplu: Cirilo"
    )

    nivel = st.selectbox(
        "🎮 Hili nivel:",
        ["Fasil", "Moderadu", "Difisil"]
    )

    st.markdown("### 📚 Nivel sira")

    st.write("🟢 **Fasil** — Adisaun, subtrasaun, multiplikasaun no divizaun simples.")
    st.write("🟡 **Moderadu** — Operasaun ho númeru boot, frazaun no númeru desimal.")
    st.write("🔴 **Difisil** — Orde operasaun no problema aplikasaun.")

    st.write("")

    if st.button("🚀 HAHÚ JOGU", use_container_width=True):

        if nome.strip() == "":
            st.warning("⚠️ Favór ida hakerek naran molok hahú.")
        else:
            st.session_state.nome = nome
            st.session_state.nivel = nivel

            # Hili no mistur pergunta
            lista = perguntas[nivel].copy()
            random.shuffle(lista)

            # Hili 5 pergunta
            st.session_state.quiz = lista[:5]

            st.session_state.indice = 0
            st.session_state.pontuasaun = 0
            st.session_state.respondidu = False
            st.session_state.resposta_utilizador = ""
            st.session_state.terminado = False
            st.session_state.iniciado = True

            st.rerun()

# ============================================================
# JOGU PRINCIPAL
# ============================================================

else:

    # -----------------------
    # FINÁL
    # -----------------------
    if st.session_state.terminado:

        pontuasaun = st.session_state.pontuasaun

        st.markdown(
            "<div class='result-box'>",
            unsafe_allow_html=True
        )

        st.markdown(f"## 🎉 Parabéns, {st.session_state.nome}!")

        st.write(
            f"Nivel: **{st.session_state.nivel}**"
        )

        st.markdown(
            f"### 🏆 Ita nia pontuasaun: {pontuasaun} / 500"
        )

        percentagem = (pontuasaun / 500) * 100

        if percentagem == 100:
            st.success(
                "🌟 PERFEITU! Ita dominá Aritmétika!"
            )
            st.balloons()

        elif percentagem >= 60:
            st.success(
                "👏 Di'ak loos! Ita halo servisu di'ak."
            )

        elif percentagem >= 40:
            st.warning(
                "💪 Di'ak ona! Kontinua pratika tan."
            )

        else:
            st.error(
                "📖 Koko tan! Aprende husi erru no hadi'a."
            )

        st.markdown("</div>", unsafe_allow_html=True)

        st.write("")

        if st.button("🔄 JOGA TAN", use_container_width=True):

            lista = perguntas[st.session_state.nivel].copy()
            random.shuffle(lista)

            st.session_state.quiz = lista[:5]
            st.session_state.indice = 0
            st.session_state.pontuasaun = 0
            st.session_state.respondidu = False
            st.session_state.resposta_utilizador = ""
            st.session_state.terminado = False

            st.rerun()

    # -----------------------
    # PERGUNTA
    # -----------------------
    else:

        pergunta_atual = st.session_state.quiz[
            st.session_state.indice
        ]

        total_pergunta = len(st.session_state.quiz)
        numero_pergunta = st.session_state.indice + 1

        # HEADER
        col1, col2, col3 = st.columns(3)

        with col1:
            st.metric(
                "👤 Jogadór",
                st.session_state.nome
            )

        with col2:
            st.metric(
                "🏆 Pontu",
                st.session_state.pontuasaun
            )

        with col3:
            st.metric(
                "🎮 Nivel",
                st.session_state.nivel
            )

        # PROGRESSO
        progresso = st.session_state.indice / total_pergunta

        st.progress(
            progresso,
            text=f"Pergunta {numero_pergunta} hosi {total_pergunta}"
        )

        st.markdown("")

        # CAIXA PERGUNTA
        st.markdown(
            "<div class='question-box'>",
            unsafe_allow_html=True
        )

        st.markdown(
            f"### ❓ Pergunta {numero_pergunta}"
        )

        st.markdown(
            f"## {pergunta_atual['pergunta']}"
        )

        st.markdown(
            "</div>",
            unsafe_allow_html=True
        )

        # OPÇAUN
        resposta = st.radio(
            "👉 Hili resposta loos:",
            pergunta_atual["opsaun"],
            index=None,
            key=f"q_{st.session_state.indice}"
        )

        # BOTÃO VERIFIKA
        if not st.session_state.respondidu:

            if st.button(
                "✅ VERIFIKA RESPOSTA",
                use_container_width=True
            ):

                if resposta is None:
                    st.warning(
                        "⚠️ Favór hili resposta ida."
                    )

                else:
                    st.session_state.respondidu = True
                    st.session_state.resposta_utilizador = resposta

                    if resposta == pergunta_atual["los"]:

                        # Pontuasaun tuir nivel
                        if st.session_state.nivel == "Fasil":
                            st.session_state.pontuasaun += 100
                        elif st.session_state.nivel == "Moderadu":
                            st.session_state.pontuasaun += 150
                        else:
                            st.session_state.pontuasaun += 200

                        st.success(
                            "🎉 SIN! Ita nia resposta loos!"
                        )

                    else:
                        st.error(
                            f"❌ Sala. Resposta loos mak: "
                            f"**{pergunta_atual['los']}**"
                        )

                    st.info(
                        f"💡 **Esplikasaun:** "
                        f"{pergunta_atual['explicasaun']}"
                    )

                    st.rerun()

        # APÓS VERIFIKA
        else:

            resposta_user = st.session_state.resposta_utilizador

            if resposta_user == pergunta_atual["los"]:
                st.success("🌟 Excelente! Ita hetan pontu!")
            else:
                st.error("📚 Aprende husi resposta ida-ne'e.")

            st.info(
                f"💡 {pergunta_atual['explicasaun']}"
            )

            # BOTÃO PERGUNTA TUIR
            if st.session_state.indice < total_pergunta - 1:

                if st.button(
                    "➡️ PERGUNTA TUIR",
                    use_container_width=True
                ):

                    st.session_state.indice += 1
                    st.session_state.respondidu = False
                    st.session_state.resposta_utilizador = ""

                    st.rerun()

            else:

                if st.button(
                    "🏁 REMATA JOGU",
                    use_container_width=True
                ):

                    st.session_state.terminado = True
                    st.rerun()

# ============================================================
# FOOTER
# ============================================================

st.markdown("---")

st.caption(
    "🧮 Aventura Aritmétika | Matemátika Klase 6 | "
    "Python + Streamlit"
)